name: Build and Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project packages
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display SoftUni Username
      run: echo "michaelalukanova"
